export const substanciasQuimicas = [
    {
      "Substancia": "1,2-Dicloroetano",
      "FormulaMolecular": "C2H4Cl2",
      "MassaMolar": "98,96",
      "PontoDeEbulicao": "83,47",
      "PontoDeFusao": "-35,4",
      "Densidade": "1,25 g/cm3",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "0,87 g/100 ml (20 °C)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Acetaldeído",
      "FormulaMolecular": "C2H4O",
      "MassaMolar": "44,05",
      "PontoDeEbulicao": "20,4",
      "PontoDeFusao": "-123,5",
      "Densidade": "0,78 g/cm3 a 20°C",
      "pH": "5 em 10g/L a 20°C",
      "SolubilidadeEmAgua": "Totalmente miscível",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Acetato de Etila",
      "FormulaMolecular": "C4H8O2",
      "MassaMolar": "88,11",
      "PontoDeEbulicao": "77,1",
      "PontoDeFusao": -83,
      "Densidade": "0,9",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "85,3g/L",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Acetato de Amila",
      "FormulaMolecular": "C7H14O2",
      "MassaMolar": "130,19",
      "PontoDeEbulicao": 142,
      "PontoDeFusao": -71,
      "Densidade": "873Kg/m3",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "0,2% a 20°C",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Acetato de Isopropila",
      "FormulaMolecular": "C5H10O2",
      "MassaMolar": "102,13",
      "PontoDeEbulicao": "88,5",
      "PontoDeFusao": "-73,4",
      "Densidade": "0,874 a 20°C",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "2,9g/100mL (20°C)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Acetato de N-Butila",
      "FormulaMolecular": "C6H12O2",
      "MassaMolar": "116,16",
      "PontoDeEbulicao": 126,
      "PontoDeFusao": "-76,3",
      "Densidade": "0,879 a 20°C",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "1g/100mL (20°C)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Acetato de Sódio",
      "FormulaMolecular": "C2H3NaO2",
      "MassaMolar": "82,03",
      "PontoDeEbulicao": "Não disponível",
      "PontoDeFusao": ">300",
      "Densidade": "1,53 g/cm3",
      "pH": "8,5 - 9,9 a 246 g/l a 25 °C",
      "SolubilidadeEmAgua": "246 g/l a 20 °C",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Acetona (Propanona)",
      "FormulaMolecular": "C3H8O3",
      "MassaMolar": "58,08",
      "PontoDeEbulicao": 56,
      "PontoDeFusao": -95,
      "Densidade": "0,792 a 20 °C",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Acetonitrila",
      "FormulaMolecular": "CH3CN",
      "MassaMolar": "41,05",
      "PontoDeEbulicao": 82,
      "PontoDeFusao": -48,
      "Densidade": "786Kg/m3",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido acético (Ácido etanóico)",
      "FormulaMolecular": "C2H4O2",
      "MassaMolar": "60,05",
      "PontoDeEbulicao": "118,1",
      "PontoDeFusao": 17,
      "Densidade": "1,05g/cm3",
      "pH": "<2",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Benzóico",
      "FormulaMolecular": "C7H6O2",
      "MassaMolar": "122,12",
      "PontoDeEbulicao": "249,2",
      "PontoDeFusao": 122,
      "Densidade": "1,27g/cm3",
      "pH": "3,1 a 20°C solução aquosa",
      "SolubilidadeEmAgua": "2,9g/L",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Ácido bórico",
      "FormulaMolecular": "H3BO3",
      "MassaMolar": "61,83",
      "PontoDeEbulicao": 300,
      "PontoDeFusao": "170,9",
      "Densidade": "1,44g/cm3",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Ácido Bromídrico",
      "FormulaMolecular": "HBr",
      "MassaMolar": "80,91",
      "PontoDeEbulicao": 122,
      "PontoDeFusao": -11,
      "Densidade": "1,49g/cm3",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Clorídrico (Solução aquosa)",
      "FormulaMolecular": "HCl",
      "MassaMolar": "36,46",
      "PontoDeEbulicao": "110° (30%)",
      "PontoDeFusao": "-144,5",
      "Densidade": "1,15 (30%)",
      "pH": "2 (solução 0,2%)",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Clorossulfônico",
      "FormulaMolecular": "HSO3Cl",
      "MassaMolar": "116,53",
      "PontoDeEbulicao": 155,
      "PontoDeFusao": -80,
      "Densidade": "1,75 a 20°C",
      "pH": "Não Aplicavel",
      "SolubilidadeEmAgua": "Reage",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Fórmico",
      "FormulaMolecular": "CH2O2",
      "MassaMolar": "46,03",
      "PontoDeEbulicao": "100,8",
      "PontoDeFusao": "8,4",
      "Densidade": "1,22g/cm3",
      "pH": "1,5",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Hipofosforoso",
      "FormulaMolecular": "H3PO2",
      "MassaMolar": 66,
      "PontoDeEbulicao": 108,
      "PontoDeFusao": "<-25",
      "Densidade": "1,49g/cm3",
      "pH": 1,
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Iodídrico",
      "FormulaMolecular": "Hl",
      "MassaMolar": "127,91",
      "PontoDeEbulicao": "-35,36",
      "PontoDeFusao": -51,
      "Densidade": "2,85g/cm3",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Ácido nítrico",
      "FormulaMolecular": "HNO3",
      "MassaMolar": "63,01",
      "PontoDeEbulicao": 83,
      "PontoDeFusao": -42,
      "Densidade": "1,51g/cm3",
      "pH": "Fortemente ácido",
      "SolubilidadeEmAgua": "Solúvel (liberação de calor)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido ortofosfórico",
      "FormulaMolecular": "H3PO4",
      "MassaMolar": "97,99",
      "PontoDeEbulicao": 158,
      "PontoDeFusao": 21,
      "Densidade": "1,88g/cm3",
      "pH": 1,
      "SolubilidadeEmAgua": "Miscível",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Sulfúrico",
      "FormulaMolecular": "H2SO4",
      "MassaMolar": "98,08",
      "PontoDeEbulicao": 338,
      "PontoDeFusao": 3,
      "Densidade": "1,84g/cm3",
      "pH": "Ácido",
      "SolubilidadeEmAgua": "Solúvel (liberação de calor)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Ácido Sulfúrico Fumegante",
      "FormulaMolecular": "H2SO4 + SO3",
      "MassaMolar": "98,08",
      "PontoDeEbulicao": "Não disponível",
      "PontoDeFusao": "Não disponível",
      "Densidade": "1,90g/cm3",
      "pH": "Não disponível",
      "SolubilidadeEmAgua": "Não disponível",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Água Destilada",
      "FormulaMolecular": "H20",
      "MassaMolar": "18,02",
      "PontoDeEbulicao": 100,
      "PontoDeFusao": 0,
      "Densidade": "997Kg/m3",
      "pH": "5-7,5",
      "SolubilidadeEmAgua": "Totalmente solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Álcool Etírico (Etanol)",
      "FormulaMolecular": "C2H6O",
      "MassaMolar": "46,07",
      "PontoDeEbulicao": "78,37",
      "PontoDeFusao": "-114,1",
      "Densidade": "789Kg/m3",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Álcool Isobutírico",
      "FormulaMolecular": "C4H8O2",
      "MassaMolar": "88,11",
      "PontoDeEbulicao": 155,
      "PontoDeFusao": -47,
      "Densidade": "970Kg/m3",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "20g/100mL (20°C)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Álcool Isopropílico",
      "FormulaMolecular": "C3H8O",
      "MassaMolar": "60,1",
      "PontoDeEbulicao": "82,6",
      "PontoDeFusao": "",
      "Densidade": "786Kg/m3",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Álcool Metílico",
      "FormulaMolecular": "CH3OH",
      "MassaMolar": "32,04",
      "PontoDeEbulicao": "64,7",
      "PontoDeFusao": "-97,6",
      "Densidade": "792Kg/m3",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "Solúvel",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Álcool N-Butílico",
      "FormulaMolecular": "C4H10O",
      "MassaMolar": "74,12",
      "PontoDeEbulicao": "117,7",
      "PontoDeFusao": "-79,9",
      "Densidade": "0,810 a 20°",
      "pH": 7,
      "SolubilidadeEmAgua": "7,8g/100mL (20°C)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Álcool N-Propílico",
      "FormulaMolecular": "C3H8O",
      "MassaMolar": "60,1",
      "PontoDeEbulicao": 97,
      "PontoDeFusao": -126,
      "Densidade": "803Kg/m3",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "Completamente Miscível",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Álcool Sec-Butílico",
      "FormulaMolecular": "C4H10O",
      "MassaMolar": "74,12",
      "PontoDeEbulicao": "99,5",
      "PontoDeFusao": "-114,7",
      "Densidade": "0,807 a 20°",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "20g/100mL (20°C)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Amônia",
      "FormulaMolecular": "NH3",
      "MassaMolar": "17,03",
      "PontoDeEbulicao": "-33,4",
      "PontoDeFusao": "-77,7",
      "Densidade": "0,682 a -33,4°",
      "pH": "Não Pertinente",
      "SolubilidadeEmAgua": "Miscivel",
      "EstadoFisico20C": "Gás"
    },
    {
      "Substancia": "Anidrido Acético",
      "FormulaMolecular": "C4H603",
      "MassaMolar": "102,09",
      "PontoDeEbulicao": 139,
      "PontoDeFusao": -73,
      "Densidade": "1,083 a 20°",
      "pH": "",
      "SolubilidadeEmAgua": "Reage lentamente e torna-se miscível",
      "EstadoFisico20C": "Líquido Aquoso"
    },
    {
      "Substancia": "Anidrido Propiônico",
      "FormulaMolecular": "C6H10O3",
      "MassaMolar": "130,1",
      "PontoDeEbulicao": 169,
      "PontoDeFusao": -45,
      "Densidade": "1,01 a 20°",
      "pH": "Não Pertinente",
      "SolubilidadeEmAgua": "Insolúvel/Reage lentamente",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Anilina (Fenilamina)",
      "FormulaMolecular": "C7H6N",
      "MassaMolar": "93,13",
      "PontoDeEbulicao": "184,2",
      "PontoDeFusao": -6,
      "Densidade": "1,022 a 20°",
      "pH": "8,1 (0,2M)",
      "SolubilidadeEmAgua": "3,7g/100mL (30°)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Azul de Metileno",
      "FormulaMolecular": "C16H18CIN3S",
      "MassaMolar": "319,85",
      "PontoDeEbulicao": "Decompõe-se",
      "PontoDeFusao": "100 a 110",
      "Densidade": "Não disponível",
      "pH": "~3",
      "SolubilidadeEmAgua": "~20g/L",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Benzaldeído",
      "FormulaMolecular": "C7H6O",
      "MassaMolar": "106,12",
      "PontoDeEbulicao": 179,
      "PontoDeFusao": -26,
      "Densidade": "1,046 a 20°",
      "pH": "Não Pertinente",
      "SolubilidadeEmAgua": "0,3g/100mL (25°)",
      "EstadoFisico20C": "Líquido Aquoso"
    },
    {
      "Substancia": "Benzeno",
      "FormulaMolecular": "C6H6",
      "MassaMolar": "78,11",
      "PontoDeEbulicao": "80,1",
      "PontoDeFusao": "5,5",
      "Densidade": "0,879 a 20°C",
      "pH": "Não Pertinente",
      "SolubilidadeEmAgua": "0,18g/100mL (25°)",
      "EstadoFisico20C": "Líquido Aquoso"
    },
    {
      "Substancia": "Bicarbonato de Potássio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Bicarbonato de sódio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Borohidreto de Sódio",
      "FormulaMolecular": "NaBH4",
      "MassaMolar": "37,83",
      "PontoDeEbulicao": "Decompõe-se",
      "PontoDeFusao": "Não Pertinente",
      "Densidade": "1,074 a 20°",
      "pH": "11 (10g/L)",
      "SolubilidadeEmAgua": "54g/100mL (25°)",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Bromobenzeno",
      "FormulaMolecular": "C6H5Br",
      "MassaMolar": 157,
      "PontoDeEbulicao": 156,
      "PontoDeFusao": "-30,6",
      "Densidade": "1,49 a 25°",
      "pH": "Não Pertinente",
      "SolubilidadeEmAgua": "0,047g/100mL (25°)",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Butilamina",
      "FormulaMolecular": "C4H11N",
      "MassaMolar": "73,14",
      "PontoDeEbulicao": "77,4",
      "PontoDeFusao": -50,
      "Densidade": "0,741 a 20°",
      "pH": "12,6 (100gL)",
      "SolubilidadeEmAgua": "Miscível",
      "EstadoFisico20C": "Líquido"
    },
    {
      "Substancia": "Carbonato de Cálcio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Carbonato de Potássio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Carbonato de Sódio Anidro",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Carvão Ativado",
      "FormulaMolecular": "C",
      "MassaMolar": 12,
      "PontoDeEbulicao": "Muito Alto",
      "PontoDeFusao": ">3500",
      "Densidade": "2 a 20°",
      "pH": "Não Pertinente",
      "SolubilidadeEmAgua": "Insolúvel",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Cicloexano",
      "FormulaMolecular": "(CH2)6",
      "MassaMolar": "84,16",
      "PontoDeEbulicao": "80,7",
      "PontoDeFusao": "6,5",
      "Densidade": "0,779 a 20°",
      "pH": "Não Pertinente",
      "SolubilidadeEmAgua": "0,015g/100mL (28,3°)",
      "EstadoFisico20C": "Líquido Aquoso"
    },
    {
      "Substancia": "Cicloexanona",
      "FormulaMolecular": "C6H10O",
      "MassaMolar": "98,15",
      "PontoDeEbulicao": "155,8",
      "PontoDeFusao": -45,
      "Densidade": "0,945 a 20°",
      "pH": "Não Disponível",
      "SolubilidadeEmAgua": "5g/100mL (20°)",
      "EstadoFisico20C": "Líquido Aquoso"
    },
    {
      "Substancia": "Cloreto de Acetila",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cloreto de Alumínio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cloreto de Amônio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cloreto de Benzoíla",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cloreto de Cálcio Anidro",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cloreto de Matileno",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cloreto de Tionila",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cloreto Mercúrico",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Clorofórmio",
      "FormulaMolecular": "CHCl3",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Cromato de Potássio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Diacetona Álcool",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Diclorometano",
      "FormulaMolecular": "CH2Cl2",
      "MassaMolar": "84,93",
      "PontoDeEbulicao": "39,8",
      "PontoDeFusao": -97,
      "Densidade": "1,322 a 20°",
      "pH": 7,
      "SolubilidadeEmAgua": "1,38g/100mL (20°)",
      "EstadoFisico20C": "Líquido Oleoso"
    },
    {
      "Substancia": "Dicromato de Potássio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Dicromato de Sódio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Dissulfeto de Carbono",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Eteno (Etileno)",
      "FormulaMolecular": "C2H4",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Éter",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Éter de Petróleo",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Éter Etílico (Etoxi-etano)",
      "FormulaMolecular": "C4H10O",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Etilamina",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Fenacetina",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Fenacetina",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Fenolftaleína",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Formamida",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Formiato de amônio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Formol (Metanal)",
      "FormulaMolecular": "CH2O",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Fósforo Vermelho",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Hidreto de Alumín io e Lítio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Hidróxido de Amônio (amoníaco em solução aquosa)",
      "FormulaMolecular": "NH4OH",
      "MassaMolar": "Não Pertinente",
      "PontoDeEbulicao": "Não Pertinente",
      "PontoDeFusao": "Não Pertinente",
      "Densidade": "0,89 a 20°",
      "pH": "11,3 (0,1M)",
      "SolubilidadeEmAgua": "Miscível",
      "EstadoFisico20C": "Líquido aquoso"
    },
    {
      "Substancia": "Hidróxido de cáucio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Hidróxido de Potássio",
      "FormulaMolecular": "KOH",
      "MassaMolar": "56,11",
      "PontoDeEbulicao": "Muito Alto",
      "PontoDeFusao": 380,
      "Densidade": "2,04 a 15°",
      "pH": "13 (0,1M)",
      "SolubilidadeEmAgua": "120g/100mL (23,9°)",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Hidróxido de sódio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Hidróxido de Sódio (Sólido)",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Hidróxido de Sódio (solução aquosa)",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Hidroxilamina",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Hipoclorito de Sódio (solução aquosa)",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Iodo (Sublimado)",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Lítio (Metálico)",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Magnésio Metálico",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Magnésio Metálico",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Manitol",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Metilamina",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Metiletilcetona",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Metilisobutilcetona",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Monobromobenzeno",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "N-Heptano",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "N-Hexano",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Nitroetano",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Orto-Toluidina",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Oxalato de Potássio",
      "FormulaMolecular": "K2C2O4",
      "MassaMolar": "184,24",
      "PontoDeEbulicao": "Decompõe-se",
      "PontoDeFusao": "Decompõe-se",
      "Densidade": "2,13 a 18,5°",
      "pH": "7,6 (0,2M)",
      "SolubilidadeEmAgua": "38,4g/100mL (25°)",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Óxido de Cálcio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Pentacloreto de fósforo",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Permanganato de potássio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Peróxido de Hidrogênio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Peróxido de Potássio",
      "FormulaMolecular": "K2O2",
      "MassaMolar": 110,
      "PontoDeEbulicao": "Decompõe-se",
      "PontoDeFusao": 490,
      "Densidade": "1 a 20°",
      "pH": ">7",
      "SolubilidadeEmAgua": "Reage",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Piridina",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Potássio Metálico",
      "FormulaMolecular": "K",
      "MassaMolar": 39,
      "PontoDeEbulicao": 774,
      "PontoDeFusao": "63,6",
      "Densidade": "0,86 a 20°",
      "pH": ">7",
      "SolubilidadeEmAgua": "Reage",
      "EstadoFisico20C": "Sólido"
    },
    {
      "Substancia": "Sódio Metálico",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Sulfato de Cálcio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Sulfato de Cobre",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Sulfato de Potássio",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Sulfato de Sódio Anidro",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Tetracloreto de Carbono",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Tetracloroetileno",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Tetrahidrofurano",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Tolueno",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Tricloroetileno",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Ureia",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    },
    {
      "Substancia": "Xileno",
      "FormulaMolecular": "",
      "MassaMolar": "",
      "PontoDeEbulicao": "",
      "PontoDeFusao": "",
      "Densidade": "",
      "pH": "",
      "SolubilidadeEmAgua": "",
      "EstadoFisico20C": ""
    }
  ]